# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('schedule', '0003_auto_20160715_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSPCEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.Event')),
                ('event_location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
            bases=('schedule.event',),
        ),
    ]
