# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    def load_data(apps, schema_editor):
        from django.core.management import call_command
        call_command("loaddata", "locations", )

    def unload_data(apps, schema_editor):
        loc = apps.get_model("locations", "Location")
        loc.objects.all().delete()

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RunPython(load_data, reverse_code=unload_data)
    ]
